#ifndef TYPEDEFS_H
#define TYPEDEFS_H

#include <cstdint>
#include <cstddef>

// Calling conventions
#define __cdecl
#define __thiscall
#define __stdcall
#define __fastcall

// Basic types
typedef uint8_t  byte;
typedef uint16_t word;
typedef uint32_t dword;
typedef uint64_t qword;
typedef uint8_t  uchar;
typedef uint32_t uint;
typedef uint16_t ushort;
typedef uint32_t ulong;
typedef int64_t  longlong;
typedef uint64_t ulonglong;

// Ghidra undefined types
typedef uint8_t  undefined;
typedef uint8_t  undefined1;
typedef uint16_t undefined2;
typedef uint32_t undefined4;
typedef uint64_t undefined8;
typedef void     code;
typedef double   float10;

// Nadeo specific base types
typedef uint32_t TimeInt32;

// Enums (defined as uint for compatibility)
typedef uint EAccountType;
typedef uint EAlignHorizontal;
typedef uint EAlignVertical;
typedef uint EArchive;
typedef uint EAvatarVariant;
typedef uint EBalanceGroup;
typedef uint EBillState;
typedef uint EBlockType;
typedef uint ECallback;
typedef uint ECardinalDir;
typedef uint EChallengeCutScene;
typedef uint EChallengeType;
typedef uint ECipherOpMode;
typedef uint ECollisionGroup;
typedef uint EContactInterest;
typedef uint EConvertMethod;
typedef uint ECpuExt;
typedef uint ECubeFace;
typedef uint EDayTime4;
typedef uint EDbgLight;
typedef uint EDecorationMusic;
typedef uint EDirectory;
typedef uint EDoMobilPtrVersion;
typedef uint EDx9Vendor;
typedef uint EDynamicType;
typedef uint EEffectMode;
typedef uint EErrorCode;
typedef uint EEvent;
typedef uint EFidType;
typedef uint EFindWay;
typedef uint EForceOpen;
typedef uint EGmSurfType;
typedef uint EGxAlphaCmp;
typedef uint EGxBlendFactor;
typedef uint EGxBlendOp;
typedef uint EGxTexAddress;
typedef uint EGxTexArg;
typedef uint EGxTexFilter;
typedef uint EGxTexOp;
typedef uint EH_epilog3;
typedef uint EHmsCorpusCat;
typedef uint EInOut;
typedef uint EInterfaceMusic;
typedef uint EInterfaceSound;
typedef uint EKindOS;
typedef uint ELightUpdate;
typedef uint ELoadGfxPerfResult;
typedef uint ELoadId;
typedef uint EMakeDir;
typedef uint EMaterialMode;
typedef uint EMessageType;
typedef uint EMobilStateQuality;
typedef uint EMode;
typedef uint EMwIconList;
typedef uint EMwSchemeTimedPatterns;
typedef uint ENormalFormat;
typedef uint EParam;
typedef uint EParamType;
typedef uint EPixelUpdate;
typedef uint EPlayerInfoArchiveState;
typedef uint EPlayerType;
typedef uint EPlugGpuPipeline;
typedef uint EPlugShaderVertexColor;
typedef uint EPlugVDcl;
typedef uint EPlugVDclType;
typedef uint EPlugVideoTimer;
typedef uint EPredictionType;
typedef uint EPreset;
typedef uint EProtocol;
typedef uint ERaceState;
typedef uint ERadius;
typedef uint EReadFileRes;
typedef uint ERealInterp;
typedef uint EReload;
typedef uint ERenderMode;
typedef uint EReplayGhostVersion;
typedef uint ERetCode;
typedef uint ERROR;
typedef uint ESailType;
typedef uint ESceneLight;
typedef uint ESceneLightUpdate;
typedef uint ESceneMobilQuality;
typedef uint ESceneVehicleParticleQuality;
typedef uint EShadowCaster;
typedef uint ESpectatorCameraTarget;
typedef uint ESpectatorCameraType;
typedef uint ESpriteColor0;
typedef uint EStack_54;
typedef uint EStackType;
typedef uint EState;
typedef uint EStatus;
typedef uint EStdGpuV;
typedef uint EStdShader2;
typedef uint ESurface;
typedef uint ETextMode;
typedef uint ETmValidateResult;
typedef uint ETurboType;
typedef uint EUpdate;
typedef uint EVar1;
typedef uint EVar10;
typedef uint EVar11;
typedef uint EVar13;
typedef uint EVar15;
typedef uint EVar16;
typedef uint EVar2;
typedef uint EVar21;
typedef uint EVar23;
typedef uint EVar27;
typedef uint EVar28;
typedef uint EVar29;
typedef uint EVar3;
typedef uint EVar31;
typedef uint EVar32;
typedef uint EVar37;
typedef uint EVar4;
typedef uint EVar5;
typedef uint EVar6;
typedef uint EVar7;
typedef uint EVar8;
typedef uint EVar9;
typedef uint EVehicleEvent;
typedef uint EVersion;
typedef uint EVolatileTreeType;
typedef uint EXCEPTION_RECORD;
typedef uint EXmlParamAction;

// Missing Classes/Structs (forward declarations or empty structs)
struct CCallback;
struct CCallbackRenderBeforeTree;
struct CCameraFxDx9;
struct CClassicBufferCrypted;
struct CConstructionImage;
struct CControlEffect;
struct CControlEffectMotion;
struct CControlField2;
struct CControlTimeLine;
struct CControlUiDockable;
struct CCrystal;
struct CCrystalEdge;
struct CDx9IndexBuffer;
struct CDx9VStreamKeeper;
struct CDynaSpecular;
struct CEditionData;
struct CFastCallback1P;
struct CFastCallback2P;
struct CFastCallback3P;
struct CFastCrypt;
struct CFastMap;
struct CFastMapTable;
struct CFastRectTable;
struct CFastStringBase;
struct CFuncPlug;
struct CFuncSegment;
struct CFuncTree;
struct CFuncWeather;
struct CGameAdvertisingNadeo;
struct CGameAdvertisingRadial;
struct CGameApp_MenuContext;
struct CGameBuddy;
struct CGameControlCameraTarget;
struct CGameControlGridCard;
struct CGameControlPlayer;
struct CGameCtnBlockInfoClip;
struct CGameCtnBlockUnit;
struct CGameCtnDecorationMood;
struct CGameCtnEditor;
struct CGameCtnFieldUnit;
struct CGameCtnMediaBlock;
struct CGameCtnMediaBlockCameraEffectShake;
struct CGameCtnMediaBlockImage;
struct CGameCtnMediaBlockText;
struct CGameCtnMediaContext;
struct CGameCtnMediaTrack;
struct CGameCtnZone;
struct CGameManialinkPage;
struct CGameNetDataDownload;
struct CGamePopUp;
struct CGameScoresVersion;
struct CGameTournament;
struct CGmCollisionBuffer;
struct CHmsPhysicalContact;
struct CHmsStateDyna;
struct CImpressionCollector;
struct CIteratorMaterial;
struct CIteratorShader;
struct CIteratorSurface;
struct CIteratorTree;
struct CIteratorVisual;
struct CLoadGeomDynaSprite;
struct CLoadGeomVertexGen;
struct CLoader;
struct CLoaderFidContainer;
struct CManoeuvre;
struct CMotionManager;
struct CMotionParticleEmitterModel;
struct CMotionWindBlocker;
struct CMwClassInfoCSceneToyBoat;
struct CMwCmdAffectParam;
struct CMwCmdAffectParamBool;
struct CMwCmdExpIso4Ident;
struct CMwCmdExpStringConcat;
struct CMwCmdFiber;
struct CMwCmdScriptVarBool;
struct CMwCmdScriptVarClass;
struct CMwNodRef;
struct CMwParamFastBuffer;
struct CMwValueStd;
struct CNetFileTransferDataToWrite;
struct CNetIPAddress;
struct CNetIPC;
struct CNetMasterServerUptoDateCheck;
struct CNetNod_CheckedArchive;
struct CNetSystemError;
struct COalAudioPort;
struct COalAudioSound;
struct CPfmHeap;
struct CPlugBitmap;
struct CPlugBitmapAddress;
struct CPlugBitmapApply;
struct CPlugBitmapRender;
struct CPlugBitmapRenderCamera;
struct CPlugBitmapRenderHemisphere;
struct CPlugBitmapRenderLightFromMap;
struct CPlugBitmapRenderShadow;
struct CPlugBitmapRenderVDepPlaneY;
struct CPlugBitmapRenderWater;
struct CPlugBitmapSampler;
struct CPlugBitmapShader;
struct CPlugBlendShapes;
struct CPlugCrystal;
struct CPlugFileAvi;
struct CPlugFileOggVorbis;
struct CPlugFileVideo;
struct CPlugFontBitmap;
struct CPlugMaterialFx;
struct CPlugMaterialFxFur;
struct CPlugMaterialFxs;
struct CPlugSoundEngine;
struct CPlugSoundMood;
struct CPlugSoundMulti;
struct CPlugSoundSurface;
struct CPlugTreeFrustum;
struct CPlugTreeGenerator;
struct CPlugTreeLight;
struct CPlugVertexStream;
struct CPlugVisualLines2D;
struct CPlugVisualStrip;
struct CPlugVisualVertexs;
struct CPlugVolumeProjector;
struct CPlugVolumeShadow;
struct CRpcCallInternal;
struct CSceneFx;
struct CSceneFxFlares;
struct CSceneInfoDrag;
struct CSceneInfoFocus;
struct CSceneInfoMouse;
struct CSceneLocation;
struct CSceneToyCharacterTunings;
struct CSceneToySeaHoule;
struct CSceneToySeaHouleFixe;
struct CSceneToySubway;
struct CSysFidNodRef;
struct CSystemWindow;
struct CTrackManiaEnvironmentManager;
struct CTrackManiaNetworkServerInfo;
struct CTrackManiaPlayer;
struct CTrackManiaPlayerProfile;
struct CUrlLinks;
struct CVirtualisedBuffer;
struct CVisionData;
struct EAccountType;
struct EAlignHorizontal;
struct EAlignVertical;
struct EArchive;
struct EAvatarVariant;
struct EBalanceGroup;
struct EBillState;
struct EBlockType;
struct ECallback;
struct ECardinalDir;
struct EChallengeCutScene;
struct EChallengeType;
struct ECipherOpMode;
struct ECollisionGroup;
struct EContactInterest;
struct EConvertMethod;
struct ECpuExt;
struct ECubeFace;
struct EDayTime4;
struct EDbgLight;
struct EDecorationMusic;
struct EDirectory;
struct EDoMobilPtrVersion;
struct EDx9Vendor;
struct EDynamicType;
struct EEffectMode;
struct EErrorCode;
struct EEvent;
struct EFidType;
struct EFindWay;
struct EForceOpen;
struct EGmSurfType;
struct EGxAlphaCmp;
struct EGxBlendFactor;
struct EGxBlendOp;
struct EGxTexAddress;
struct EGxTexFilter;
struct EGxTexOp;
struct EHmsCorpusCat;
struct EInOut;
struct EInterfaceMusic;
struct EInterfaceSound;
struct ELightUpdate;
struct ELoadId;
struct EMakeDir;
struct EMaterialMode;
struct EMessageType;
struct EMobilStateQuality;
struct EMode;
struct EMwIconList;
struct EMwSchemeTimedPatterns;
struct ENormalFormat;
struct EParam;
struct EParamType;
struct EPlayerInfoArchiveState;
struct EPlayerType;
struct EPlugGpuPipeline;
struct EPlugShaderVertexColor;
struct EPlugVDcl;
struct EPlugVDclType;
struct EPlugVideoTimer;
struct EPredictionType;
struct EPreset;
struct EProtocol;
struct ERaceState;
struct ERadius;
struct EReadFileRes;
struct ERealInterp;
struct EReload;
struct ERenderMode;
struct EReplayGhostVersion;
struct ERetCode;
struct ESailType;
struct ESceneLight;
struct ESceneLightUpdate;
struct ESceneMobilQuality;
struct ESceneVehicleParticleQuality;
struct EShadowCaster;
struct ESpectatorCameraTarget;
struct ESpectatorCameraType;
struct ESpriteColor0;
struct EStackType;
struct EState;
struct EStatus;
struct EStdGpuV;
struct EStdShader2;
struct ESurface;
struct ETextMode;
struct ETmValidateResult;
struct ETurboType;
struct EVehicleEvent;
struct EVersion;
struct EVolatileTreeType;
struct SAgainstGroup;
struct SAvatarMessage;
struct SBill;
struct SBinding;
struct SBitmapSpecular;
struct SBlendableVals;
struct SBlock;
struct SBlockEditInfo;
struct SBlockState;
struct SBuildPageParams;
struct SCachedValue;
struct SCallStackFidContext;
struct SCallbackList;
struct SCameraPreset;
struct SCasterCat;
struct SCell;
struct SCharStyle;
struct SClippingFrustum;
struct SColOctreeCell;
struct SContext;
struct SCriteria;
struct SDelayedToSort64b;
struct SDesc;
struct SDeviceMat;
struct SDicoEntry;
struct SDownloadProgress;
struct SDxDefine;
struct SDynaPart;
struct SEmitParams;
struct SEngine;
struct SEnvMod;
struct SEnvironment;
struct SEventStunt;
struct SFastKey;
struct SFeature;
struct SFillValue;
struct SFlags;
struct SFormat;
struct SFrameLadderRankingsStepOld;
struct SFxCat;
struct SFxValue;
struct SGmSmoothReal2;
struct SGroup;
struct SGxPixRect;
struct SHMAC_MD5_Data;
struct SHeader;
struct SHeaderCommunity;
struct SHeaderFolderDep;
struct SHeaderUserData;
struct SHemiInfo;
struct SHistoryPoint;
struct SHmsCameraLocation;
struct SHmsItem_CallbackSortCustom_Elem;
struct SHmsPhysicalCollision;
struct SHmsVPackerObject;
struct SIdRemapTable;
struct SImpressionRecord;
struct SInputActionDesc;
struct SInputEvent;
struct SInstanceId;
struct SKey;
struct SKeyVal;
struct SLadderResult;
struct SLadderStats;
struct SLightBallLoc;
struct SLightSpotLoc;
struct SLoadDesc;
struct SLoadedLight;
struct SLocal;
struct SLocationAlloc;
struct SManuallyLoadedFid;
struct SMappedAction;
struct SMedalsInfo;
struct SMenuLeaguePathStepInfos;
struct SMeshOctreeCell;
struct SMwFiberContext;
struct SMwParamInfo;
struct SMwSchemeTimedProperties;
struct SMwTimedValueInstant;
struct SNat128;
struct SNationConfig;
struct SNetConfig;
struct SNetStateBuffer;
struct SNewTriangleVert;
struct SOccWheel;
struct SOfficialRecordState;
struct SOldChars;
struct SPackedDesc;
struct SParam;
struct SParamEffect;
struct SParam_Fid;
struct SParam_Fid_Common;
struct SParam_Fids;
struct SParam_Id;
struct SParam_Set;
struct SParseTreeLight;
struct SPart;
struct SPartState;
struct SPlayerInfosForTargetting;
struct SPlayerOrGhost;
struct SPlugGpuLoadFx;
struct SPlugTreeInRenderFlags;
struct SPlugTreeLocatedPair;
struct SPlugTreeOptimCriteria;
struct SPlugTreeOptimGroup;
struct SPlugTreeOptimTravel;
struct SPlugVisibleId;
struct SPointInTri;
struct SPredictionTypeVector;
struct SQuadTreeMeshUv;
struct SQueuedNetConnectionLessNod;
struct SRasterizeVertex;
struct SRealTimeState;
struct SRenderInfo;
struct SRenderShaderParam;
struct SReplayToValidateData;
struct SRequestElement;
struct SRequestInfos;
struct SRpcForcedScores;
struct SRpcPlayerInfo;
struct SRtWheelToCpu;
struct SRumble;
struct SSailManoeuvre;
struct SSampler;
struct SSamplerCat;
struct SSamplerState;
struct SScanner;
struct SSceneLoc;
struct SShaderCustom;
struct SShadowCameraInter;
struct SSimulationWheel;
struct SSmoothingGroup;
struct SSpecularHighlight;
struct SSpecularSubMapCat;
struct SSpriteF;
struct SStackLocation;
struct SStartParameters;
struct SState;
struct SStdGpuMask;
struct SStreamContext;
struct SStreamDecl;
struct SSurfaceHandler;
struct SSwitch;
struct STarget;
struct STexStageState;
struct STextSettings;
struct STextureRenderCat;
struct STransformDesc;
struct STri_PosTexTgt;
struct SUser;
struct SUserData;
struct SVehicleBallState;
struct SVehicleCarState;
struct SVehicleState;
struct SVisualArm;
struct SVisualHandler;
struct SVisualLight;
struct SVisualWheel;
struct SVolatileTreePointer;
struct SZone;

// Common Nadeo Templates (opaque for now)
template<typename T> struct CFastBuffer { uint count; T* data; };
template<typename T> struct CFastArray { uint count; uint capacity; T* data; };
template<typename T, int N, typename S> struct CFixedArray { T data[N]; };

#endif // TYPEDEFS_H
