#include "CMwClassInfo.hpp"
#include <cstring>

// Global pointer to the start of the ClassInfo linked list 
// (Mapped to DAT_00d73ba8 in the assembly)
extern CMwClassInfo* g_FirstClassInfo; 

// =================================================
// Function: CMwClassInfo::BuildTree
// Traverses the flat linked list and wires up the parent-child tree.
// =================================================
void CMwClassInfo::BuildTree(CMwClassInfo* root)
{
    CMwClassInfo* current = root;
    
    while (current != nullptr) {
        if (current->m_parent != nullptr) {
            // Register this class as a child of its parent
            current->m_parent->AddChild(current);
        }
        current = current->m_next;
    }
}

// =================================================
// Function: CMwClassInfo::FindFromClassName
// =================================================
CMwClassInfo* CMwClassInfo::FindFromClassName(CFastString* classNameStr)
{
    if (g_FirstClassInfo == nullptr) {
        return nullptr;
    }

    CMwClassInfo* current = g_FirstClassInfo;

    do {
        if (current->m_className != nullptr) {
            // CFastString::Compare is used heavily in the engine.
            // Ghidra showed a manual strlen loop (pcVar2 - local_8), which the 
            // CFastString implementation handles internally.
            if (classNameStr->Compare(current->m_className)) {
                return current;
            }
        }
        current = current->m_next;
    } while (current != nullptr);

    return nullptr;
}

// =================================================
// Function: CMwClassInfo::IsMwParamIdEqualName
// Resolves a parameter ID, extracts its string name, and compares it.
// =================================================
bool CMwClassInfo::IsMwParamIdEqualName(uint32_t paramId, const char* paramName) const
{
    if (this == nullptr) {
        return false;
    }

    // 1. Verify the parameter belongs to this class
    // The top 20 bits of a param ID represent its owning Class ID
    if ((paramId & 0xFFFFF000) != m_classId) {
        return false;
    }

    // 2. Extract the local index (Bottom 12 bits)
    unsigned int paramIndex = paramId & 0xFFF;
    if (paramIndex >= m_paramCount) {
        return false;
    }

    // 3. Look up the parameter metadata string
    // Offset 0x10 in the SMwParamInfo struct points to the string literal name
    SMwParamInfo* paramInfo = m_params[paramIndex];
    const char* internalName = *(const char**)((char*)paramInfo + 0x10);

    // 4. Inline strcmp generated by MSVC, collapsed into standard C++
    if (internalName == nullptr || paramName == nullptr) {
        return false;
    }
    
    return std::strcmp(paramName, internalName) == 0;
}

// =================================================
// Function: CMwClassInfo::MwGetNearestFather
// Climbs the inheritance tree to find the first matching ancestor.
// =================================================
uint32_t CMwClassInfo::MwGetNearestFather(uint32_t count, uint32_t* parentIds) const
{
    const CMwClassInfo* current = this;

    do {
        // Check if current class ID is in the requested array
        for (uint32_t i = 0; i < count; ++i) {
            if (current->m_classId == parentIds[i]) {
                return i; // Return the index of the matching ancestor ID
            }
        }

        // Climb up to the parent
        current = current->m_parent;
        
    } while (current != nullptr);

    // 0xFFFFFFFF (-1) indicates no match found in the inheritance chain
    return 0xFFFFFFFF;
}

// =================================================
// Function: CMwClassInfo::AddChild
// Stub for the intrusive tree builder logic.
// =================================================
void CMwClassInfo::AddChild(CMwClassInfo* childClass) {
    // Typical intrusive sibling-list insertion
    childClass->m_sibling = m_firstChild;
    m_firstChild = childClass;
}